name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Sync project dependencies
        run: uv sync --dev --frozen

      - name: Ruff lint
        run: uv run ruff check

      - name: Ty type check
        run: uv run ty check

      - name: Run test suite
        run: uv run pytest
